title: "최애의 독서 | Archive"
description: "아이돌, 셀럽, 그리고 나의 최애가 읽은 책들을 한곳에 모았습니다."
url: "[https://hwiruruk.github.io](https://hwiruruk.github.io)"
baseurl: "/favoread"

# 개별 인물 페이지 생성 규칙
collections:
  celebs:
    output: true
    permalink: /celeb/:title/
